[repository]
repository = "opendal:sftp"
password-command = "/home/julian/.local/bin/systemd-pass-fallback rustic-password security/rustic-password"

[repository.options]
endpoint = "192.168.255.42"
user = "madagascar-backup"
key = "/home/julian/.ssh/madagascar-backup"
root = "/rustic"
known_hosts_strategy = "strict"

[forget]
keep-daily = 7
keep-weekly = 5

[[backup.snapshots]]
name = "password-store"
sources = ["/home/julian/.password-store"]
