[repository]
repository = "rclone:backblaze:madagascar-backups"
password-file = "/home/julian/Private/passwords/rustic-password"

[forget]
keep-daily = 14
keep-weekly = 5

[[backup.snapshots]]
sources = ["/home/julian/Private"]

[[backup.snapshots]]
sources = ["/home/julian/Documents"]

[[backup.snapshots]]
sources = ["/home/julian/Media/Pictures"]

[[backup.snapshots]]
sources = ["/home/julian/Media/Videos"]
