[repository]
repository = "rclone:backblaze:madagascar-backups"
password-command = "/home/julian/.local/bin/systemd-pass-fallback rustic-password madagascar/rustic/password"

[forget]
keep-daily = 7
keep-weekly = 5

[[backup.snapshots]]
sources = ["/home/julian/Documents"]

[[backup.snapshots]]
sources = ["/home/julian/Media/Pictures"]

[[backup.snapshots]]
sources = ["/home/julian/Media/Videos"]

[[backup.snapshots]]
sources = ["/home/julian/.password-store"]

[[backup.snapshots]]
sources = ["/home/julian/.local/share/mail/fastmail"]
globs = ["!.notmuch", '!.uidvalidity', '!.mbsyncstate']

[[backup.snapshots]]
sources = ["/home/julian/.local/share/contacts"]

[[backup.snapshots]]
sources = ["/home/julian/.local/share/calendars"]
