# Dim the screen after 2 minutes
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Suspend the computer after 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
